// Shape.h – Specification
#pragma once            // generated by Visual Studio
#include <iostream>     // for input/output
#include <string>       // for string class
using namespace std;

class Shape
{
  // data (properties)
  private:
     string type;
     string colour;
  // functions (methods)
  public:
     Shape();	             	// default constructor
     Shape(string, string);	// parameterized constructor
     void setType(string);	// set type
     string getType();		// get type
     void setColour(string);	// set colour
     string getColour();		// get colour
     double findArea();		// calculate area
     void print();		// print Shape properties
};
